theme: jekyll-theme-cayman
title: Kraft Manuals 
tagline: User manuals for the open source project Kraft
baseurl: https://dragotin.github.io/krafthandbook/

show_downloads: false

author:
  name: The Kraft Project
  url: https://volle-kraft-voraus.de
